config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'pages#home'

  resources :users, only: [ :show, :edit, :update ]

  resources :hubots, only: [ :index, :show, :new, :create, :edit, :update, :destroy ] do
    resources :bookings, only: [ :create, :show, :update ] do
      resources :reviews, only: [ :new, :create ]
    end
  end
  get 'search', to: 'hubots#search'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :hubot
  has_many :reviews
  validates :check_in, timeliness: { on_or_before: lambda { :check_out }, type: :date }
end

app/models/hubot.rb
class Hubot < ApplicationRecord
  # Association
  belongs_to :user
  has_many :reviews, through: :bookings
  has_many :bookings

  # Validations
  validates :name, presence: true, allow_blank: false
  validates :category, presence: true, allow_blank: false
  validates :manufacturer, presence: true, allow_blank: false
  validates :model, presence: true, allow_blank: false
  validates :age, numericality: { only_integer: true }
  validates :turing_test_score, numericality: { only_integer: true }, inclusion: { in: (1..100).to_a }
  validates :price_per_hour, numericality: { only_integer: true }
  validates :autonomy, numericality: true
  validates :charging_time, numericality: true
  validates :gender, inclusion: { in: ["male","female"], message:"%{value} is not a valid gender", allow_nil: false }
  validates :skin_color, inclusion: { in: ["white","asian","brown","black"], message:"%{value} is not a valid skin color", allow_nil: false }

  # Photo Upload
  mount_uploader :photo, PhotoUploader

  CATEGORIES = [
    "Sport coach",
    "Guard",
    "Housemaid",
    "Personal shopper",
    "Sexbot",
    "Veterinary",
    "Family bot",
    "Collector",
    "Guardian",
    "Dance",
    "Butler",
    "Paramedical",
    "Ceo",
    "Teacher",
    "Community Manager",
    "Nanny"
  ]
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :booking

  # Validations
  validates :content, presence: true
  validates :rating, presence: true, numericality: { only_integer: true }, inclusion: { in: (1..5).to_a }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :hubots, dependent: :destroy
  has_many :reviews, through: :bookings
  has_many :bookings

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  # Photo Upload
  mount_uploader :photo, PhotoUploader

  # Validations
  validates :email, presence: true, uniqueness: { case_sensitive: false }, on: :create
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def create
    @hubot = Hubot.find(params[:hubot_id])
    @booking = Booking.new
    @booking.check_in = DateTime.strptime(params["check_in"], '%m/%d/%Y %H:%M %p')
    @booking.check_out = DateTime.strptime(params["check_out"], '%m/%d/%Y %H:%M %p')
    @booking.hubot = @hubot
    check_in = @booking.check_in
    check_out = @booking.check_out
    @booking.hubot = @hubot
    @booking.user = current_user
    @hours = ( DateTime.strptime(params["check_out"], '%m/%d/%Y %H:%M %p').to_i - DateTime.strptime(params["check_in"], '%m/%d/%Y %H:%M %p').to_i ).fdiv(3600)
    @booking.total_price = @hours * @hubot.price_per_hour

    if @booking.save
      redirect_to user_path(current_user)
    else
      render "hubots/show"
    end
  end

  def index
    @user = current_user
  end

  def show
    @user = current_user
    @booking = Booking.find(params)
  end

  def update
    booking = Booking.find(params[:booking_id])
    if params[:booking_action] == "accept_booking"
      booking.update(status: "accepted")
    elsif params[:booking_action] == "reject_booking"
      booking.update(status: "rejected")
    end
    redirect_to user_path(current_user)
  end

  private

  def booking_params
    params.require(:booking).permit(:check_in, :check_out)
  end
end

app/controllers/hubots_controller.rb
class HubotsController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :index, :search, :show ]
  before_action :get_search_params, only: [ :search, :show ]

  def search
    @hubots = Hubot.where("category LIKE ?", params[:category])
  end

  def index
    @hubots = Hubot.all
  end

  def show
    @hubot = Hubot.find(params[:id])
    @new_booking = Booking.new
    @new_review = Review.new
    unless @checkin.nil? && @checkout.nil?
      @hours = ( DateTime.strptime(@checkout, '%m/%d/%Y %H:%M %p').to_i - DateTime.strptime(@checkin, '%m/%d/%Y %H:%M %p').to_i ).fdiv(3600)
    end
    # if
    # @booking =
  end

  def new
    @hubot = Hubot.new
    @user = current_user
  end

  def create
    @hubot = Hubot.new(hubot_params)
    @hubot.user = current_user
    if @hubot.save
      redirect_to hubot_path(@hubot)
    else
      render 'new'
    end
  end

  def edit
    @hubot = Hubot.find(params[:id])
  end

  def update
    @hubot = Hubot.find(params[:id])
    @hubot.update(hubot_params)
    redirect_to hubots_path(@hubot)
  end

  def destroy
    @hubot = Hubot.find(params[:id])
    @hubot.destroy
    redirect_to hubots_path(@hubot)
  end

  private

  def hubot_params
    params.require(:hubot).permit(:name, :category, :manufacturer, :model, :age,
                                  :turing_test_score, :price_per_hour, :autonomy,
                                  :charging_time, :gender, :skin_color, :photo, :photo_cache)
  end

  def get_search_params
    @category = params["category"]
    @checkin = params["check_in"]
    @checkout = params["check_out"]
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_booking, only: [:new, :create]

  def new
    @review = Review.new
  end

  def create
    # @booking = Booking.new(params[:booking_id])
    @review = Review.new(review_params)
    @review.booking = @booking
    if @review.save
      redirect_to booking_path(@booking)
    else
      render 'new'
      # render 'hubots/show'
    end
  end

  private

  def set_booking
    @booking = Booking.find(params[:booking_id])
  end

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def passthru
    binding.pry
    super
  end

  def twitter
    user = User.find_for_twitter_oauth(request.env['omniauth.auth'])

    if user.persisted?
      sign_in_and_redirect user, event: :authentication
      set_flash_message(:notice, :success, kind: 'Twitter') if is_navigational_format?
    else
      session['devise.twitter_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  skip_before_action :authenticate_user!, only: [ :show, :hubots, :edit, :update ]
  before_action :set_user, only: [ :show, :hubots, :edit, :update ]

  # GET /users/:id
  def show
    @user_coordinates = { lat: @user.latitude, lng: @user.longitude }
    @user_pending_bookings = @user.bookings.where(status: "pending")
    @user_current_bookings = @user.bookings.where(status: "accepted").where("check_out < ?", Time.now)
    @user_old_bookings = @user.bookings.where(status: "accepted").where("check_out > ?", Time.now)
  end

  def edit
  end

  def update
    @user.update(user_params)
    if @user.save
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  # GET /users/:id/hubots
  def hubots
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:email, :first_name, :last_name, :gender, :photo, :photo_cache)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/hubots_helper.rb
module HubotsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/hubots/_form.html.erb
<%= simple_form_for (hubot), html: { class: 'form-horizontal' },
  wrapper: :horizontal_form do |f| %>
  <%= f.error_notification %>

  <%= f.input :name %>
  <%= f.input :age %>
  <%= f.input :gender, collection: ["female", "male"] %>
  <%= f.input :skin_color, collection: [ "white", "asian", "brown", "black"] %>
  <%= f.input :category %>
  <%= f.input :manufacturer %>
  <%= f.input :model %>
  <%= f.input :turing_test_score %>
  <%= f.input :autonomy %>
  <%= f.input :charging_time %>
  <%= f.input :price_per_hour %>
  <%= f.input :photo %>
  <%= f.input :photo_cache, as: :hidden %>
  <%= f.button :submit %>
<% end %>

app/views/hubots/edit.html.erb
<h1>Edit:</h1>

<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-offset-2 col-sm-8 panel panel-info">

      <h2>Edit your Hubot</h2>

      <%= render "form", hubot: @hubot %>

      <%= link_to "← Back", hubots_path, class: "btn btn-default" %>

    </div>
  </div>
</div>

app/views/hubots/index.html.erb
<% content_for(:title_tag) do %>
  Hubots
<% end %>


<div class="container">
<h1>All hubots</h1>

  <%= link_to 'Add your Hubot!', new_hubot_path, class: "btn btn-default" %>

  <div class="row">
    <% @hubots.each do |hubot| %>
      <div class="col-xs-6 col-sm-4 col-md-3">
        <%= render 'shared/hubot', hubot: hubot %>
      </div>
    <% end %>
  </div>
</div>

app/views/hubots/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-offset-3 col-md-6 col-sm-offset-2 col-sm-8 col-xs-offset-1 col-xs-10 authentication">

      <h2>Add a new Hubot</h2>

      <%= render "form", hubot: @hubot %>

      <%= link_to "← Back", hubots_path, class: "btn btn-default" %>

    </div>
  </div>
</div>

app/views/hubots/search.html.erb
<% content_for(:title_tag) do %>
  Search Results
<% end %>

<div class="wrapper bg-grey padded">
  <div class="container">
    <%= link_to "Back", root_path, class: "btn btn-default" %>
    <div class="row">

      <div class="col-xs-12 heading">
        <div class="row">
          <div class="col-xs-12 col-md-6">
            <h3>
              Search results for <strong><%= params["category"] %></strong><br>
            </h3>
          </div>
          <div class="col-xs-12 col-md-6">
            <h3>
              <span style="display: inline-block; width: 3em">from</span> <strong><%= params["check_in"] %></strong><br>
              <span style="display: inline-block; width: 3em">to</span> <strong><%= params["check_out"] %></strong>
            </h3>
          </div>
        </div>
        <hr>
      </div>

      <% @hubots.each do |hubot| %>
        <div class="col-xs-6 col-sm-4 col-md-3">
          <%= render 'shared/hubot', hubot: hubot %>
        </div>
      <% end %>

    </div>
  </div>
</div>

app/views/hubots/show.html.erb
<% content_for(:title_tag) do %>
  <%= @hubot.name %>
<% end %>

<div class="wrapper bg-grey padded">
  <div class="container">

    <div class="row">

      <aside class="col-xs-12 col-md-4 col-md-offset-1 pull-right fixed-lg">
        <div class="row">

          <% if @hubot.photo? %>
            <div class="col-xs-12 col-sm-5 col-md-12 hubot-avatar" style="background-image: url('<%= cl_image_path @hubot.photo %>'), linear-gradient(-225deg, rgba(0,0,0,0.2) 0%, rgba(0,0,0,0.2) 100%)">
          </div>
          <% else %>
            <div class="col-xs-12 col-sm-5 col-md-12 hubot-avatar" style="background-image: linear-gradient(-225deg, rgba(0,0,0,0.2) 0%, rgba(0,0,0,0.2) 100%)">
          </div>
          <% end %>


          <div class="col-xs-12 col-sm-7 col-md-12 hubot-booking">
            <form class="form" action="#" method="get">
              <div class="form-group" id="check_in">
                <div id='datetimepicker'>
                  <label for="check_in">Check in</label>
                  <input type="text" name="check_in" class="form-control datetimepicker" id="check_in" placeholder="Check In" value="<%= @checkin if @checkin %>">
                </div>
              </div>

              <div class="form-group" id="check_out">
                <div id='datetimepicker'>
                  <label for="check_out">Check out</label>
                  <input type="text" name="check_out" class="form-control datetimepicker" id="check_out" placeholder="Check Out" value="<%= @checkout if @checkout %>">
                </div>
              </div>
              <div class="row">
                <div class="form-group col-xs-6" id="booking-hours">
                  <label for="total-hours">Total time</label>
                  <div class="input-group">
                    <input type="text" name="total-hours" class="form-control" id="total-hours" value="<%= @hours if @hours %>" readonly>
                    <div class="input-group-addon">h</div>
                  </div>
                </div>
                <div class="form-group col-xs-6" id="booking-deposit">
                  <label for="deposit">Deposit</label>
                  <div class="input-group">
                    <input type="number" name="deposit" class="form-control" id="deposit" value="<%= @hubot.deposit ? @hubot.deposit : "0" %>" readonly>
                    <div class="input-group-addon">$</div>
                  </div>
                </div>
              </div>
              <div class="form-group" id="book">
                <!-- Button trigger modal -->
                <button type="button" class="btn btn-primary pull-right" data-toggle="modal" data-target="#myModal">Book Now</button>
                <h4 id="total-price">Total: <strong>$<%= @hubot.price_per_hour * @hours if @hours %></strong></h4>
              </div>
            </form>
          </div>

        </div> <!-- /.row-->
      </aside> <!-- /aside-->


      <div class="col-xs-12 col-md-7 hubot-infos">

        <%= link_to "<i class='material-icons md-48'>arrow_back</i>".html_safe, :back, class: "btn btn-back" %><br>

        <span class="hubot-model"><%= @hubot.model %></span> <span style="opacity: 0.25">|</span>
        <span class="hubot-category"><%= @hubot.category %></span>
        <h1 class="hubot-name"><%= @hubot.name %></h1>
        <div class="top-right rating rating-large text-center">
          <span class="rating-unit"><%= rand(3..5) %></span><span class="rating-decimal">.<%= rand(0..5) %></span>
        </div>
        <span>
          Owner: <%= link_to user_path(@hubot.user) do %>
            <%= image_tag "johndoe.jpg", class:"avatar avatar-large" %>
            <%= @hubot.user.first_name %>
          <% end %>
        </span>

        <hr>

        <h3>Description</h3>
        <p class="hubot-description"><%= @hubot.description %></p>

        <hr>

        <div class="hubot-details">

          <h3>Details</h3>

          <div class="row">
            <div class="col-md-2">
              <h6>Infos</h6>
            </div> <!-- /.col-->
            <div class="col-md-5">
              <ul>
                <li><span>Age:</span> <strong><%= @hubot.age %></strong></li>
                <li><span>Gender:</span> <strong><%= @hubot.gender %></strong></li>
                <li><span>Skin color:</span> <strong><%= @hubot.skin_color %></strong></li>
                <li><span>Manufacturer:</span> <strong><%= @hubot.manufacturer %></strong></li>
              </ul>
            </div> <!-- /.col-->
            <div class="col-md-5">
              <ul>
                <li><span>Turing test score:</span> <strong><%= @hubot.turing_test_score %>%</strong></li>
                <li><span>Autonomy:</span> <strong><%= @hubot.autonomy %> hours</strong></li>
                <li><span>Charging time:</span> <strong><%= @hubot.charging_time %> hours</strong></li>
                <li><span>Price</span> <strong>$<%= @hubot.price_per_hour %>/h</strong></li>
              </ul>
            </div>
          </div> <!-- /.row-->

          <hr>

          <div class="row">
            <div class="col-md-2">
              <h6>Accessories</h6>
            </div> <!-- /.col-->
            <div class="col-md-5">
              <ul>
                <li><span>Accessory 1:</span> </strong></li>
                <li><span>Accessory 2:</span> </strong></li>
                <li><span>Accessory 3:</span> </strong></li>
                <li><span>Accessory 4:</span> </strong></li>
              </ul>
            </div> <!-- /.col-->
            <div class="col-md-5">
              <ul>
                <li><span>Accessory 5:</span> </strong></li>
                <li><span>Accessory 6:</span> </strong></li>
                <li><span>Accessory 7:</span> </strong></li>
                <li><span>Accessory 8:</span> </strong></li>
              </ul>
            </div> <!-- /.col-->
          </div> <!-- /.row-->

        </div> <!-- /.hubot-details-->

      </div> <!-- /.hubot-infos-->
    </div> <!-- /.row-->


    <!-- Modal -->
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h5 class="modal-title" id="myModalLabel">Booking confirmation</h5>
          </div>
          <div class="modal-body">
            <h4>You’re going to book <%= @hubot.user.first_name %>’s hubot</h4>
            <p class="mono"><strong><%= @hubot.name %></strong>, <%= @hubot.model %> hubot</p>
            <p class="mono">from <strong><%= @checkin %></strong><br>
              to <strong><%= @checkout %></strong>
            </p>
            <p class="mono">Total price: <strong>$<%= @hubot.price_per_hour * @hours if @hours %></strong></p>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
            <%= link_to "Confirm", hubot_bookings_path(@hubot, check_in: @checkin, check_out: @checkout, hubot: @hubot, user: current_user), method: :post, class: "btn btn-primary" %>
          </div>
        </div>
      </div>
    </div> <!-- /.modal -->


  </div> <!-- /.container -->
</div> <!-- /.wrapper -->

<hr>

<%#= link_to 'Rate this Hubot', new_hubot_booking_review_path(@hubot, @booking) %>

<% @hubot.reviews.each do |review| %>
  <%= review.content %>
  <%= review.rating %>
<% end %>

app/views/reviews/new.html.erb
<%= simple_form_for [@booking, @review] do |f| %>
  <%= f.error_notification %>

  <%= f.input :content %>
  <%= f.input :rating, collection: 0..5 %>

  <%= f.button :submit %>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <a href="/" class="navbar-wagon-brand">
    <%= image_tag(asset_path 'logo.svg') %>
  </a>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Search form -->
<!--     <form action="" class="navbar-wagon-search">
      <input type="text" class="navbar-wagon-search-input" placeholder="Search something">
      <button type="submit" class="navbar-wagon-search-btn">
        <i class="fa fa-search"></i>
      </button>
    </form> -->

    <!-- Text link -->
    <!-- <a href="" class="navbar-wagon-item navbar-wagon-link">Contact</a> -->

    <!-- Text link -->
    <!-- <a href="" class="navbar-wagon-item navbar-wagon-link">Team</a> -->

    <!-- Notification link-->
    <!-- <a href="" class="navbar-wagon-item navbar-wagon-link">
      <div class="badge-container">
        <i class="fa fa-envelope-o"></i>
        <div class="badge badge-blue">3</div>
      </div>
    </a> -->

    <!-- Profile picture and dropdown -->
    <% if user_signed_in? %>
      <%= link_to "Rent your hubot", new_hubot_path, class:'navbar-wagon-item btn btn-primary btn-atsugi' %>
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <img src=<%= asset_path "johndoe.jpg" %> class="avatar avatar-medium dropdown-toggle" id="navbar-wagon-menu" data-toggle="dropdown">
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to "My account", user_path(current_user) %>
            </li>
            <li>
              <%= link_to "My bookings", user_path(current_user) %>
            </li>
            <li><%= link_to "Log Out", destroy_user_session_path(@user), method: :delete %></li>
          </ul>
        </div>
      </div>

    <!-- Button (call-to-action) -->
    <% else %>
      <%= link_to "LOGIN", new_user_session_path %>
      <%= link_to "Create account", new_hubot_path, class:'navbar-wagon-item btn btn-primary btn-atsugi' %>
    <% end %>


    <!-- <a href="" class="navbar-wagon-item navbar-wagon-button btn">Sign-in / Sign-up</a> -->
  </div>

  <!-- Dropdown appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<% content_for(:title_tag) do %>
  <%= @user.first_name + @user.last_name %>
<% end %>

<%= link_to "← Back", :back, class: "btn btn-default btn-back" %>
<div class="container">

  <div class="row">
    <div class="col-md-2">

      <% if @user.photo %>
        <%= cl_image_tag @user.photo, class:"avatar avatar-xxlarge" %>
      <% end %>

    </div>
    <div class="col-md-10">
        <h1><%= @user.first_name %> <%= @user.last_name %></h1>
        <% if @user == current_user %>
          <h3>Welcome to your dashboad !</h3>
        <% end %>
        <p><%= @user.description %></p>
    </div>
  </div>

  <!-- #################################################################### -->
  <!-- tabs headers -->

  <div class="row">
    <div class="tabs">

      <a class="tab active" data-target="#profile">
        <h3>
          <%= @user == current_user ? "My profile infos" : "Profile infos" %>
        </h3>
      </a>
      <% if @user == current_user %>
        <a class="tab" data-target="#bookings">
          <h3>
          My bookings
          <% if @user.bookings.count > 0 %>
            (<%= @user.bookings.count %>)
          <% end %>
          </h3>
        </a>
      <% end %>

      <a class="tab" data-target="#hubots">
        <h3>
          <%= @user == current_user ? "My hubots" : "Hubots" %>
          <% if @user.hubots.count > 0 %>
            (<%= @user.hubots.count %>)
          <% end %>
        </h3>
      </a>

    </div>
  </div>

  <!-- #################################################################### -->
  <!-- tabs contents -->

  <div class="row">

    <!-- ############    PROFILE    ############### -->

    <div class="tab-content" id="profile">
      <h4>
        About <%= @user == current_user ? "you" : @user.first_name %>
      </h4>
      <p><%= @user.description %></p>
      <h4><%= @user == current_user ? "Your" : @user.first_name %> infos</h4>
      <table class="table-striped">
        <tr>
          <td>email</td>
          <td><%= @user.email %></td>
        </tr>
        <tr>
          <td>Phone</td>
          <td><%= @user.phone_number %></td>
        </tr>
        <tr>
          <td>Address</td>
          <td><%= @user.address %></td>
        </tr>
        <tr>
          <td>GPS Coordinates</td>
          <td><%= @user_coordinates[:lat] %>, <%= @user_coordinates[:lng] %></td>
        </tr>
      </table>
      <hr>
      <%= link_to 'Edit', edit_user_path(@user), class: "btn btn-primary" %>
    </div>

    <!-- ############    BOOKINGS    ############### -->

    <div class="tab-content hidden" id="bookings">
      <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">

      <!-- ################################# -->
      <!-- Tag lists -->

      <%= link_to "Pending bookings", "#pending-bookings", class: "btn btn-default" %>
      <% if %>
        <%= link_to "Current bookings", "#current-bookings", class: "btn btn-default" %>
        <%= link_to "Old bookings", "#old-bookings", class: "btn btn-default" %>
      <% end %>
      </div>

      <!-- ################################# -->
      <!-- Pending bookings of current_user (waiting for acceptance from owner) -->

      <h4 id="pending-bookings">Your pendind bookings (<%= @user_pending_bookings.count %>)</h4>

      <% @user_pending_bookings.each do |booking| %>
        <%= render 'shared/hubot_booking_details', booking: booking %>
      <% end %>

      <!-- ################################# -->
      <!-- Current bookings of current_user -->

      <h4 id="current-bookings">Your Current Bookings (<%= @user_current_bookings.count %>)</h4>
      <% @user_current_bookings.each do |booking| %>
        <%= render 'shared/hubot_booking_details', booking: booking %>
      <% end %>
      <% if @user_current_bookings.count == 0 %>
        <p> You have no booking currently!</p>
        <%= link_to "find a Hubot !", hubots_path, class: "btn btn-default" %>
      <% end %>

      <!-- ################################# -->
      <!-- Current bookings of current_user -->

      <h4 id="old-bookings">Your Old Bookings (<%= @user_old_bookings.count %>)</h4>
      <% @user_old_bookings.each do |booking| %>
        <%= render 'shared/hubot_booking_details', booking: booking %>
      <% end %>
      <% if @user_old_bookings.count == 0 %>
        <p> You have no old bookings yet!</p>
      <% end %>


    </div>

    <!-- ############    HUBOTS    ############### -->

    <div class="tab-content hidden" id="hubots">

      <!-- Pending bookings for hubots -->
        <!-- TODO -->

      <!-- Currently booked hubots -->
        <!-- TODO -->

      <!-- All hubots -->

      <h4><%= @user == current_user ? "My" : @user.first_name + "'s" %> hubots :</h4>
        <% @user.hubots.each do |hubot| %>
          <div class="col-xs-6 col-sm-4 col-md-3">
            <%= render 'shared/hubot', hubot: hubot %>
          </div>
        <% end %>
    </div>

  </div>
</div>

<!-- ################################ -->

<% content_for(:after_js) do %>
  <%= javascript_tag do %>
    $(document).ready(function() {
      var coord = <%= raw @user_coordinates.to_json %>;
      console.log('User coordinates are ' + coord.lat + ', ' + coord.lng);

      $('.tab').on('click', function(event) {
        $('.tab').removeClass('active');
        $(this).addClass('active');
        $(".tab-content").addClass('hidden');
        $($(this).data('target')).removeClass('hidden');
      });
    });
  <% end %>
<% end %>